### ISSUE TITLE
Outras ferramentas utilizadas

### ISSUE THREAD

**Issue by jasondavindev** [epiresdasilva/super-serverless-sample#1]
Na tech talk foi comentado que fez a utilização de outras ferramentas, porém que não obtiveram sucesso.
Seria interessante documentar as outras ferramentas utilizadas e qual foram as limitações que não as tornaram eligíveis para o case.

**Comment by epiresdasilva** [comment]
Legal @jasondavindev, acabei não colocando isso mesmo aqui e faz todo sentido. Vou escrever isso para complementar o `readme`. Obrigado!

**Comment by epiresdasilva** [comment]
@jasondavindev realizei um ajuste no README para adicionar a seção `Desafio da definição da arquitetura`.
